"""empty message

Revision ID: e745593aeecf
Revises: 
Create Date: 2022-12-06 21:50:04.177652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e745593aeecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('intent_name', sa.String(length=255), nullable=True),
    sa.Column('action_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Text(length=4294000000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_sender_id'), 'events', ['sender_id'], unique=False)
    op.create_table('events_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('key2find', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectures_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=255), nullable=True),
    sa.Column('free_input', sa.Boolean(), nullable=True),
    sa.Column('response_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('text', sa.Text(length=4294000000), nullable=True),
    sa.Column('text2', sa.Text(length=4294000000), nullable=True),
    sa.Column('text3', sa.Text(length=4294000000), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectures_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('text2match', sa.Text(length=4294000000), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('answer_type', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(length=4294000000), nullable=True),
    sa.Column('text2', sa.Text(length=4294000000), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Boolean(), nullable=True),
    sa.Column('following_action', sa.String(length=255), nullable=True),
    sa.Column('following_action_id', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['lectures_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectures_answers')
    op.drop_table('lectures_steps')
    op.drop_table('lectures')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('planned_tasks')
    op.drop_table('events_slots')
    op.drop_index(op.f('ix_events_sender_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
